version: '3.8'

services:
  web:
    build: .
    depends_on:
      - redis
    expose:
      - "5000"

  redis:
    image: redis:latest

  nginx:
    image: nginx:latest
    ports:
      - "5004:5004"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - web
